services:
  - type: web
    name: giguat
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "true"
